### PR TITLE
Customize K Chart UI

### PR DESCRIPTION
**Pull request by karanchuri**
What wasn't in the existing system?
- Ability to customise UI of KChartWidget

What this PR solves?
- In KChartWidget we will have to add ChartStyle and ChartColors object so that we can change it dynamically.

### CODE REVIEW

**Comment by mafanwei** [comment]
Thank you for your contribution.
Have you tested it yet?

**Comment by karanchuri** [comment]
Yes, have tested with the line chart as well as ohlc graph.
Below is video url of my test with the line chart.
https://user-images.githubusercontent.com/29534520/117970252-149f5100-b346-11eb-99d5-bb9953827325.mp4

Also please note this is a major change as there are changes in KChartWidget required params.

**Comment by mafanwei** [comment]
Looks great.
I'll check it later.
Thank you for your contribution.

**Comment by karanchuri** [comment]
Please update the flutter library in https://pub.dev/packages/k_chart

**Comment by mafanwei** [comment]
done

**Comment by karanchuri** [comment]
Thanks ✌🏼

**Pull request merged**
